### ISSUE TITLE
Extruder rubbing and Shaving the filament that couldn't move upward.

### ISSUE THREAD

**Issue by jeffgram** [davidramiro/Marlin-Ai3M-2.0.x#1]
Honestly, the issue happened right after I flashed your Marlin 2.0 beta FW from website Github. My machine X axis carriage was turning sharply left and made a weird sound, which everything came as a mess. Therefore, i updated the stock FW back to the old version. For I guess it affected Temperature system too(i am not really sure). I occasionally doubted every single part of my 3d printer. The obvious problem is that the Mega S Titan extruder rotary part was rotating but i could see it was rubbing and shaving the filament wire in middle of the extruder, which also made sound like 'tak tak tak'  and the filament barely barely moved upwards. I replaced the Mega extruder with old one Mega i3, but still the same. I also replaced the hotend, yet it is sill the same as I thought the temperature had an issue.

I guess i have to give up my 3D printer hobby as I am losing my hope and confidence. 

Best regards, 

Jeff

**Comment by davidramiro** [comment]
Since you contacted me by mail before with many different issues - why did you flash 2.0? It's clearly marked as 

**Beta build  - Not for production use.**

Anyways, this firmware works fine, it has already been tested my several different people. Since you had all kinds of issues with your printers (also, telling from your last email, switching to manufacturer firmware did not fix your issues).

Funnily enough, you opened a similar issue on @MNieddu91's firmware - did you actually use his firmware without even owning a BLtouch? Please refrain from clogging up our issue sections or my email inbox any further and start using one of the established search engines. 

Have a nice day.
